### PR TITLE
testing: not intended for merge, inspect logs of passing tests to verify e2e indeterminsim issue

### PR DESCRIPTION
**Pull request by colin-axner**
## Description

Collecting logs of all passing tests in the gh actions environment. Based on investigation with @chatton, we have a suspicion that indeterministically docker is overlapping port bindings between chain a and chain b within both IP4 and IP6 domains. Specially that chain b might bind to `[::]:port-on-chain-a` which is used for p2p on chain b and rpc on chain a

Evidence: 
On this [failure](https://github.com/cosmos/ibc-go/actions/runs/4426328387/jobs/7762621374) we see:
>post failed: Post "http://localhost:32789/": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\""

on chain-a-val-3 for **rpc** port we see the following binding:
`0.0.0.0:32789`

on chain-b-val-3 for **p2p** port we see the following binding:
`[::]:32789`

The logs for chain-b-val-3 contain:
>Inbound Peer rejected                        module=p2p err="auth failure: secret conn failed: proto: illegal wireType 7" numPeers=4

In the interchain test logs we see:
>logger.go:130: 2023-03-15T12:44:58.226Z	INFO	Cosmos chain node started	{"chain_id": "chain-a", "test": "TestInterchainAccountsGovTestSuite/TestInterchainAccountsGovIntegration", "container": "chain-a-val-3-TestInterchainAccountsGovTestSuite_TestInterchainAccountsGovIntegration", "rpc_port": "localhost:32789"}

That is, an http request is intended for chain-a-val-3 on `localhost:32789` but it appears chain-b-val-3 is accepting the request on its p2p port thus resulting in a failed secret handshake. The p2p request is replied to with a public key causing the http response to be improperly parsed

We are collecting the docker inspection of all passing tests to ensure that there are no overlapping/mismatching port bindings for ip4/ip6 as this would confirm that the overlapping and mismatching of docker port bindings is the root issue

closes: #XXXX

### Commit Message / Changelog Entry

```bash
type: commit message
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by damiannolan** [comment]
Nice work on all this investigation ❤️  Looks like we may be close to root cause!

**Comment by chatton** [comment]
Looking into these logs vs a failing test, the port bindings look weird.

In a Passing test:

```json
{
			"1234/tcp": [
				{
					"HostIp": "0.0.0.0",
					"HostPort": "32793"
				},
				{
					"HostIp": "::",
					"HostPort": "32793"
				}
			],
			"1317/tcp": [
				{
					"HostIp": "0.0.0.0",
					"HostPort": "32787"
				},
				{
					"HostIp": "::",
					"HostPort": "32787"
				}
			],
			"26656/tcp": [
				{
					"HostIp": "0.0.0.0",
					"HostPort": "32779"
				},
				{
					"HostIp": "::",
					"HostPort": "32779"
				}
			],
			"26657/tcp": [
				{
					"HostIp": "0.0.0.0",
					"HostPort": "32775"
				},
				{
					"HostIp": "::",
					"HostPort": "32775"
				}
			],
			"9090/tcp": [
				{
					"HostIp": "0.0.0.0",
					"HostPort": "32783"
				},
				{
					"HostIp": "::",
					"HostPort": "32783"
				}
			]
		}
```

The ipv4 and ipv6 host ports align while in a failing test


```json
{
			"1234/tcp": [
				{
					"HostIp": "0.0.0.0",
					"HostPort": "32822"
				},
				{
					"HostIp": "::",
					"HostPort": "32815"
				}
			],
			"1317/tcp": [
				{
					"HostIp": "0.0.0.0",
					"HostPort": "32812"
				},
				{
					"HostIp": "::",
					"HostPort": "32807"
				}
			],
			"26656/tcp": [
				{
					"HostIp": "0.0.0.0",
					"HostPort": "32791"
				},
				{
					"HostIp": "::",
					"HostPort": "32789"
				}
			],
			"26657/tcp": [
				{
					"HostIp": "0.0.0.0",
					"HostPort": "32784"
				},
				{
					"HostIp": "::",
					"HostPort": "32783"
				}
			],
			"9090/tcp": [
				{
					"HostIp": "0.0.0.0",
					"HostPort": "32805"
				},
				{
					"HostIp": "::",
					"HostPort": "32801"
				}
			]
		}
```

they all differ.

**Comment by damiannolan** [comment]
should we close this now? cc. @colin-axner @chatton

**Comment by chatton** [comment]
yes we should be able to close this, thanks guys 👍

**Pull request closed without merging**
