### PR TITLE
deps: update wasm-clients to ibcv8 and SDK v0.50.x

### PR DESCRIPTION
**Pull request by faddat**
- update wasmVM
- shore: use 08-wasm specific events instead of 02-client ones
- use go 1.21 for wasm client
- update expected values
- rebuild protos
- Revert "update expected values"
- update Dockerfile with correct wasmvm
- Implement appmodule.AppModule interface
- Unit tests: temporarily disable grandpa testing, update TestInitializeTendermint(), remove unnecessary test from TestConsensusStateValidateBasic(), change the update state result's height type.
- TestVerifyMembershipGrandpa working again
- TestVerifyNonMembershipGrandpa, TestInitializeGrandpa, TestStatusGrandpa, and TestExportGenesisGrandpa working again
- TestCheckSubstituteAndUpdateStateGrandpa, TestVerifyHeaderGrandpa, TestUpdateStateGrandpa, TestVerifyUpgradeGrandpa working again
- Run linter
- Add instructions for re-creating grandpa test data
- Add space after comment delimiter
- tidy, please the linter

## Description

This PR upgrades the wasm-clients feature branch to ibc v8.0.x and cosmos-sdk v0.50.x

In order to do this, it was necessary to drop support for 32 bit arm cpus:

* https://github.com/CosmWasm/wasmvm/tree/v1.4.0

### Commit Message / Changelog Entry

```bash
deps: update wasm-clients to ibcv8 and SDK v0.50.x
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

## Review Notes

* most of the "changed files" are just updating import paths
* this PR can be reduced in size by merging:
  * #4603 
  * #4605 
  * #4608 
  * #4607 

... and maybe a few others

## Attribution

@misko9 contributed a series of commits that were cherry picked into this branch, and made today's work possible. 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [ x Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by faddat** [comment]
Note: my hope here is that we can get wasm clients into v8. 

Please feel free to let us know here or in slack if there is anything we can do to help make that happen

**Comment by faddat** [comment]
2nd note: the wasm client has a few tests failing, will address tomorrow.  Given the size of this one, I'm still quite open to reviews, and so I'm leaving this on "ready for review"

**Comment by faddat** [comment]
I am going to put this on draft again, I think I might need to recreate the branch.

**Comment by crodriguezvega** [comment]
> Note: my hope here is that we can get wasm clients into v8.

I am afraid that will not be possible. We cannot change v8's scope at this point anymore. We can release 08-wasm in a v8.1 release.

**Comment by faddat** [comment]
@colin-axner honestly that makes sense.  I'll try and keep a branch refreshed so that 8.1 will be a simple matter and doesn't delay v8.

🖖

**Comment by crodriguezvega** [comment]
@faddat I think I'd actually prefer if this PR is only concerned with updating `feat/wasm-clients` with the changes from main and keep out any other changes from other 08-wasm branches (Steve's and others). Then we can merge the PRs independently of each other.

And actually, to elaborate a bit more on my previous comment: we might not even need to tag ibc-go 8.1 to support 08-wasm on v8.x. Since 08-wasm has its own go.mod we just need to tag a version of 08-wasm that is pinned to ibc-go v8.0.0.

**Comment by faddat** [comment]
entirely great points!  Thank you :)

Will return to this item tomorrow :).

**Pull request closed without merging**
