### PR TITLE
Remove sdk.Result from application callbacks #215

### LINKED ISSUE #215: Remove sdk.Result from application callbacks
## Summary

The IBC handler discards these [results](https://github.com/cosmos/ibc-go/blob/832044782f10fbd4ec720da4f4950095c52a48f9/modules/core/05-port/types/module.go#L76). They are an artifact of older code which now provides no value except more code for applications

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

### PR DESCRIPTION
**Pull request by smadarasmi**
## Description

Closes #215 by removing `sdk.Result` from the IBC Module
-->

closes: #215 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by colin-axner — APPROVED** [review]
LGTM, this needs a changelog entry and an entry in the migration docs for going from ibc-go 1.0 -> 2.0 (this will not be included in 1.0)

I will try to push these to this branch

**Comment by colin-axner** [comment]
I was unable to push to your branch so I made a [pr](https://github.com/smadarasmi/ibc-go/pull/1)

Thanks for the contribution

**Comment by smadarasmi** [comment]
@colin-axner Thanks for the prompt feedback. I've merged ur PR into this branch. Please let me know if any other issues.

**Comment by colin-axner** [comment]
Thanks again for the contribution @smadarasmi! The pr is ready for auto merge

**Pull request merged**
