### PR TITLE
imp(testing): use testing.TB instead of testing.T

### PR DESCRIPTION
**Pull request by fedekunze**
## Description

Currently, the testing package only supports unit testing through `testing.T`. This PR refactors the ibc testing package to support `testing.B` (benchmarks) and `testing.F` (fuzz) tests.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by fedekunze** [comment]
tests failures seem to be unrelated

**Comment by damiannolan** [comment]
> tests failures seem to be unrelated

sometimes e2e tests will fail intermittently with docker network related errors, I wouldn't worry about it. 
I kicked off the failing test to run again.

**Review by damiannolan — APPROVED** [review]
🙏

**Review by colin-axner — APPROVED** [review]
Thanks @fedekunze!

**Pull request merged**
