### PR TITLE
chore (api)!: remove capabilities from SendPacket

### PR DESCRIPTION
**Pull request by bznein**
## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by colin-axner — APPROVED** [review]
Woo! Great work! 

For reference to other viewers. While we have not adjusted the `SendPacket` to go through an rpc on core IBC, this is still safe to remove as we rely on the security principles guarded by the bank keeper. Modules which can access the go api must not be malicious (otherwise they can send coins from any account to any other account). The same principle is being applied by removing this code. It was always true that a malicious module could bypass the channel capability anyways (by embedding the scoped keeper of another module)

**Comment by bznein** [comment]
It's probably better to have this one merged https://github.com/cosmos/ibc-go/pull/7089 before we merge any removal of capabilities, to avoid merge conflicts on that PR

**Review by damiannolan — APPROVED** [review]
Nice 🔴 diffs!

**Review by chatton — APPROVED** [review]
:axe: love the diff!

**Pull request merged**
