### PR TITLE
Adding generic contains method

### PR DESCRIPTION
**Pull request by DimitrisJim**
## Description

Cherry picked from the channel upgradability branch for #3400 

closes: #XXXX

### Commit Message / Changelog Entry

```bash
imp: Adding generic contains method
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by DimitrisJim** [comment]
Q: I add tests for it or overkill?

**Comment by damiannolan** [comment]
> Q: I add tests for it or overkill?

I'd be happy with some simple test cases with strings/ints

**Review by colin-axner — APPROVED** [review]
Nice one! I believe this can replace the usage of the contains function in `03-connection/keeper/verify.go`. Happy to see changed in a follow up pr

**Comment by DimitrisJim** [comment]
> I believe this can replace the usage of the contains function in 03-connection/keeper/verify.go. Happy to see changed in a follow up pr

Yeah, there was someone asking to do that in the issue you've opened on it hence why I thought it'd be a good idea to get this in now.

**Review by AdityaSripal — APPROVED** [review]
Looks good @DimitrisJim !

**Comment by chatton** [comment]
looks like linting is failing @DimitrisJim 

make sure to run `make lint-fix`  (although looks like a typo, not sure if it can fix it automatically!)

**Pull request merged**
