### PR TITLE
deps: update interchaintest to latest upstream code

### PR DESCRIPTION
**Pull request by faddat**
## Description

This PR updates interchaintest to the latest upstream 
code. 

### Commit Message / Changelog Entry

```bash
deps: update interchaintest to latest upstream code
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by faddat** [comment]
Note: this seems to cause numerous issues. 

We'll try and work on it from here.

**Comment by faddat** [comment]
Okay, so this turns out to be a very happy surprise. Basically, our tests were using plain go math int 64.

So what we need to do is just update the tests. I am currently updating the tests, and have also included a vendor folder in this PR, which I will be taking out but I would love it if someone from the IBC team could just give it a little peek because then I could make the one fairly minor upstream change to ICT and then this PR should be good to go after completing the conversion of the math to use the SDK math style.

**Comment by faddat** [comment]
Ok, so -- that was a bit of an adventure, but I think I've got it set now.  Basically in some places we needed to use sdkmath and in other palces we needed to convert sdkmath to int64

**Comment by faddat** [comment]
hi @crodriguezvega I think that this is going to work now.  I think it is also a good idea to look at interactions between interchaintest and ibc-go, so that we can upstream some changes.

**Comment by faddat** [comment]
I believe that I'm going to need a member of the IBC team to please rerun failed jobs until they all pass. You can use this as an indicator of flaky tests, which I'm not certain of, but this is definitely my feeling at this time.

**Comment by faddat** [comment]
Also if only the same tests failed during this run then maybe some of the changes are causing the problem?

Not sure yet but will check tomorrow

**Comment by DimitrisJim** [comment]
yeah, haven't had time to look into it but re-runs won't help, interchaintest is returning an `sdkmath.Int` and we expect a normal int64, this is happening in most errors I saw when going through the logs.

**Comment by faddat** [comment]
Oh well if that's in the current errors, that's relatively easy to fix. Very nice!

I'll run through again tomorrow.

**Comment by faddat** [comment]
You did it!

Great work!

**Review by colin-axner — APPROVED** [review]
This is great, thanks @faddat! Appreciate that this was pulled into its own pr, very easy to review!

**Comment by colin-axner** [comment]
Thank you @catShaark as well!

**Review by charleenfei — APPROVED** [review]
thank you! 🚀

**Review by DimitrisJim — APPROVED** [review]

**Pull request merged**
