### PR TITLE
Chore: fix every typos

### PR DESCRIPTION
**Pull request by hoangdv2429**
## Description

This PR will fix every typo on the current repository.

closes: #XXXX

### Commit Message / Changelog Entry

chore: fix every typos

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by colin-axner — APPROVED** [review]
Thank you @hoangdv2429! That was quite a bit of typos

**Comment by hoangdv2429** [comment]
@colin-axner if possible, can I add another CI for auto pointing out typo per PR sir ?

**Comment by hoangdv2429** [comment]
I think we need to make a list of tools for this job and list they pros and cons here.

**Comment by hoangdv2429** [comment]
I'm thinking of using codespell to make CI check. It's pretty reliable. when I'm listing all the typos, all the words that need to be excluded are `clienta` , `connectiona` and `lastest`. Otherwise, there is no false detection. wdyt @DimitrisJim @colin-axner .

**Comment by hoangdv2429** [comment]
Can someone rerun that e2e, I got lots of weird e2e test fail today.

**Comment by hoangdv2429** [comment]
@DimitrisJim  Thank you for replying! Waiting for the CI is indeed a chronic pain. I'm changing my approach to add this as a pre-commit hook. I think it's better!

**Pull request merged**
