### PR TITLE
Chore: consistent argument order

### PR DESCRIPTION
**Pull request by ThanhNhann**
## Description

closes: #4311 

This PR updates the order of arguments in verification functions 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by damiannolan — COMMENTED** [review]
Thank you @ThanhNhann! 

I understand this was decided in the related issue but I don't think I agree with the argument order in this PR. 

For example, most of the channel related verification funcs here accept the tuple (portID, channelID, sequence) in order to build the key path for which we prove. 
The changes in PR breaks the association between (portID/channelID) and (sequence) by separating them in the arg list for verifying commitments, acks etc. IMHO this is a code smell. 

Personally I'd be more in favour of changing the new verify funcs for channel upgrades to conform to the older arg ordering. 

Happy to hear from others on this.

**Comment by crodriguezvega** [comment]
Thank you for opening this PR, @ThanhNhann. We discussed internally [@damiannolan's comment above](https://github.com/cosmos/ibc-go/pull/4545#pullrequestreview-1609039361) and we agreed to the following: we will keep the ordering of arguments as is for the existing verification functions and we should change the order in the verification functions that have been added for channel upgradability ([`VerifyChannelUpgradeError`](https://github.com/cosmos/ibc-go/blob/b0cb9f136e304b8a01cbc654acc50c24412d40cc/modules/core/03-connection/keeper/verify.go#L370), [`VerifyChannelUpgradeErrorAbsence`](https://github.com/cosmos/ibc-go/blob/b0cb9f136e304b8a01cbc654acc50c24412d40cc/modules/core/03-connection/keeper/verify.go#L413) and [`VerifyChannelUpgrade`](https://github.com/cosmos/ibc-go/blob/b0cb9f136e304b8a01cbc654acc50c24412d40cc/modules/core/03-connection/keeper/verify.go#L413)). The order of the arguments in those functions should be: ctx, connection, height, proof, key, value (not application for absence verification). So for example, for `VerifyChannelUpgradeError` it would be `ctx`, `connection`, `proofHeight`, `proofErrorReceipt`, `portID`, `channelID`, `errorReceipt`.

I hope this makes sense. Would you be able then to adjust this PR accordingly? Let us know if you have any questions; thank you very much in advance!

**Comment by crodriguezvega** [comment]
@ThanhNhann I pushed the changes mentioned in the comment above. I hope that's ok.

**Comment by ThanhNhann** [comment]
hi @crodriguezvega, sorry for the late reply, can you rerun the CI for this PR?

**Comment by crodriguezvega** [comment]
@ThanhNhann can you rebase with main? I think that should fix the problems with the link in the markdown.

**Review by colin-axner — APPROVED** [review]
ACK pending ci passing (which I think will occur when #4773 is merged as it fixes the ci on the upgrades branch)

Thanks again @ThanhNhann for your contributions!

**Review by damiannolan — APPROVED** [review]
Thank you @ThanhNhann! Apologies for the delay on this one

Will merge after https://github.com/cosmos/ibc-go/pull/4773 as Colin mentioned 🙏

**Pull request merged**
