### PR TITLE
chore: removing legacy params subspaces for sdk modules

### PR DESCRIPTION
**Pull request by damiannolan**
## Description

Removes params subspaces for sdk modules which have now migrated to self managed module params.

closes: #3141

### Commit Message / Changelog Entry

```bash
chore: removing legacy params subspaces for sdk modules
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by colin-axner — APPROVED** [review]
Nice one!

**Comment by crodriguezvega** [comment]
This should be backported to v7.1.x only, right?

**Comment by damiannolan** [comment]
> This should be backported to v7.1.x only, right?

The branch doesn't exist yet tho, right? 
I thought the process was to branch off `release/v7.0.x` as `release/v7.1.x` and then merge main into the latter. I can add the label for v7.1.0 anyways!

**Review by chatton — APPROVED** [review]
LGTM!

**Comment by crodriguezvega** [comment]
> I thought the process was to branch off release/v7.0.x as release/v7.1.x and then merge main into the latter. I can add the label for v7.1.0 anyways!

Yes, I haven't created it yet, just waiting a bit to see if we finally release v7 with or without localhost. But having the labels in the PRs already will make it easier to figure out later what needs to be backported.

> then merge main into the latter

But I don't think we should merge main into v7.1.x, otherwise we might bring some API breaking changes...

**Pull request merged**
