### PR TITLE
imp: add version to tm headers in ibctesting (release/v6.3.x)

### PR DESCRIPTION
**Pull request by damiannolan**
## Description

Take changes forward from: https://github.com/cosmos/ibc-go/pull/6099
This PR targets release/v6.3.x.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by damiannolan** [comment]
Noting here that I'm not sure that this is needed given that v6 is an EOL release line. Feel free to close if you think, cc. @crodriguezvega

**Comment by rootulp** [comment]
You're spot on that celestia-app is currently blocked on upgrading ibc-go because we maintain a Cosmos SDK fork that is currently on v0.46.x. We don't have firm plans but I think we'll try to bump to Cosmos SDK v0.50+ and upgrade directly to ibc-go/v8 after our next hard-fork.

**Comment by damiannolan** [comment]
> You're spot on that celestia-app is currently blocked on upgrading ibc-go because we maintain a Cosmos SDK fork that is currently on v0.46.x. We don't have firm plans but I think we'll try to bump to Cosmos SDK v0.50+ and upgrade directly to ibc-go/v8 after our next hard-fork.

Hey @rootulp! I wanted to quickly discuss this with the team before merging since v6 is EOL. 
Happy to merge this and we'll tag a v6.3.1 for you with this change, however we won't make an official release via GitHub since the release line is EOL. I can let you know when the tag is available!

**Comment by rootulp** [comment]
Awesome, thanks Damian! A v6.3.1 tag will be super helpful for us :)

**Pull request merged**
