### PR TITLE
added ChannelId to MsgChannelOpenInitResponse

### PR DESCRIPTION
**Pull request by rigelrozanski**
## Description
added ChannelId to MsgChannelOpenInitResponse
this is needed for distribution within interchain security

Also my go imports didn't like go metrics so I had to add the go-metrics alias
---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by AdityaSripal — APPROVED** [review]
Thanks @rigelrozanski ! 

Context for the other folks reviewing: This is a problem in general not just for CCV. But currently, in CCV we want to initiate a transfer channel and know what the channelID is.

So if we want to do this as part of third-party module logic, it's currently impossible with the codebase. Since, if you try to use channelKeeper directly you will need portCapability; and a third party module will not have transfer's portCapability.

So we have to use the MsgServer, but the response doesn't include the channelID which we need since then we want to send transfer packets over the established channel.

So this is going to be an issue for any third-party module that wants to initialize a channel of a different IBC application and then use that channel to send packets over

**Review by colin-axner — APPROVED** [review]
Thanks @rigelrozanski! 

This should be targeted towards the `main` branch though?

**Comment by AdityaSripal** [comment]
Ahh yes, I think this is a PR tracked to the branch we're using as a dependency for interchain-security. If you could open a PR targetting main with just these diffs that would be much appreciated. Thanks @rigelrozanski !

**Comment by seantking** [comment]
> Thanks @rigelrozanski !
> 
> Context for the other folks reviewing: This is a problem in general not just for CCV. But currently, in CCV we want to initiate a transfer channel and know what the channelID is.
> 
> So if we want to do this as part of third-party module logic, it's currently impossible with the codebase. Since, if you try to use channelKeeper directly you will need portCapability; and a third party module will not have transfer's portCapability.
> 
> So we have to use the MsgServer, but the response doesn't include the channelID which we need since then we want to send transfer packets over the established channel.
> 
> So this is going to be an issue for any third-party module that wants to initialize a channel of a different IBC application and then use that channel to send packets over

Thanks for the context! Super cool. When/Why are you opening a transfer channel with CCV (just interested)? 

I can definitely see this being really useful for other IBC applications.

**Review by seantking — APPROVED** [review]

**Comment by rigelrozanski** [comment]
Closing in favour of merge to main https://github.com/cosmos/ibc-go/pull/848

**Pull request closed without merging**
