### PR TITLE
fix(transfer): change Authorization interface implementation in proto file

### PR DESCRIPTION
**Pull request by Vvaradinov**
## Description

Hi team, I noticed a suspicious error when testing out our Evmos local node with the recent backported changes in v6.2.

```go
Error: unable to create codec descriptor: unable to get proto name for implementing type / for interface cosmos.v1beta1.Authorization
```
I've located a typo in the TransferAuthorization proto message using the wrong interface name for Authorization. After changing it the error goes away and the local node is started correctly.

closes: #XXXX

### Commit Message / Changelog Entry

```bash
type: commit message
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by damiannolan — APPROVED** [review]
Interesting that this is a requirement on sdk v0.46. We had an issue https://github.com/cosmos/ibc-go/issues/2977 opened to correctly use the fully qualified proto type URL for these interfaces. 

--- 

I decided to check: its because the [v0.46 code](https://github.com/cosmos/cosmos-sdk/blob/v0.46.12/x/authz/codec.go#L32) does not register the interface as `cosmos.authz.v1beta1.Authorization` but `cosmos.v1beta1.Authorization` lol

**Comment by colin-axner** [comment]
> Interesting that this is a requirement on sdk v0.46. We had an issue #2977 opened to correctly use the fully qualified proto type URL for these interfaces.
> 
> I decided to check: its because the [v0.46 code](https://github.com/cosmos/cosmos-sdk/blob/v0.46.12/x/authz/codec.go#L32) does not register the interface as `cosmos.authz.v1beta1.Authorization` but `cosmos.v1beta1.Authorization` lol

Does `cosmos.v1beta1.Authorization` work? Or was #2977 only in reference to v0.47+?

**Comment by crodriguezvega** [comment]
Are we happy using `Authorization` or should we use `cosmos.v1beta1.Authorization`?

**Comment by damiannolan** [comment]
> Are we happy using `Authorization` or should we use `cosmos.v1beta1.Authorization`?

I think either is fine. IIRC correctly the fully qualified name isn't a requirement until > sdk 0.47

**Review by crodriguezvega — APPROVED** [review]

**Review by chatton — APPROVED** [review]
LGTM

**Pull request merged**
