### PR TITLE
feat: add version to the header

### PR DESCRIPTION
**Pull request by ninabarbakadze**
## Description

context: https://github.com/celestiaorg/celestia-app/issues/3137

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by ninabarbakadze** [comment]
> ah, sorry for updating the branch, didn't see this was in draft and have built the habbit. Feel free to roll that back if needed.

no worries! I don't think i need to roll back.

**Review by damiannolan — APPROVED** [review]
This looks good to me! Would be fine with breaking the API in latest. We could handle that ourselves in a separate PR with the similar diffs. Either way this is testing code but we generally stick to API breaks in major versions even for our testing lib as there is a number of consumers using it.

**Comment by ninabarbakadze** [comment]
> > ah, sorry for updating the branch, didn't see this was in draft and have built the habbit. Feel free to roll that back if needed.
> 
> no worries! I don't think i need to roll back.

could you please take another look? @DimitrisJim thank you! :)

**Comment by damiannolan** [comment]
Hi @ninabarbakadze, we no longer maintain our own `ConsensusParams` on the `main` branch for testing purposes and instead are using `simtestutil.DefaultConsensusParams` in sdk v0.50. It looks to me that they do use the `Version` field in there. I think those changes should be PR'd to the sdk and we can pick them up on `main` when available and make the associated changes with them - this would be required as well for backporting to ibc-go/v8.

I have taken your changes forward to the ibc-go/v7 release line in a PR here: https://github.com/cosmos/ibc-go/pull/6180

Also should note that ibc-go/v6 is EOL

**Comment by rootulp** [comment]
Thanks! Can this please also be included in a v6.3.x?

**Comment by damiannolan** [comment]
Hey @ninabarbakadze, @rootulp, I merged on `release/v6.3.x` and tagged https://github.com/cosmos/ibc-go/tree/v6.3.1.

Will close this PR since its stale and you're already ahead of v6.2 :)

**Pull request merged**
