### PR TITLE
ibc-go 7.1

### PR DESCRIPTION
**Pull request by faddat**
## Description

ibc-go with wasm client for composable testnet

### Commit Message / Changelog Entry

```bash
type: commit message
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by crodriguezvega** [comment]
@faddat Thank you for this PR. I really appreciate it, but I think it is still too soon to open a PR for wasm clients. The fork needs to be updated with the latest changes from v7.1, and there are still improvements that we are planning to push to have the feature as close as we would like to have it in ibc-go, so that the PR review becomes easier as faster. Besides, I think it would be fair for Strangelove (and Composable) to open the PR from their fork of ibc-go, so that they are recognized for their work. So I will close this PR for now. Again, I appreciate your intentions, but I think the moment is not right yet.

**Comment by faddat** [comment]
Hi Carlos, just so that you are aware, notional is working with both strangelove and composable on this at this time.  All three teams are focused on making packets fly between polkadot style networks and the greater cosmos at large.

Would you be opposed to my reopening this as a draft pull request?

All three teams share the mutual concern of getting this code, even if it is in an incomplete state, into this repository, so that it is more visible. We would like for external teams to be able to comment on, view, and iterate on this code.

One thing I did want to ask about though, you said that the branch here was missing some changes?

Would you mind letting me know what those changes are? Because I would be very happy to modify this PR in any way needed.

**Comment by Sen-Com** [comment]
I second this, @faddat. Too much fragmentation...

**Comment by crodriguezvega** [comment]
@faddat Thanks for your comment and great to hear that you're also contributing to move this feature forward!

In my honest opinion I think a (draft) PR should be opened at least with these 2 pre-requisites:

- When the feature branch from the fork is up to date with the tip of main of ibc-go. This PR you opened had 419 files changed! So not being up to date with the latest of ibc-go creates a lot of noise and frustration for reviewers.
- The PR should be opened from Strangelove's fork. That's where all the development is happening and where all different teams (Strangelove, Composable, Notional and also Interchain) are contributing, so it makes sense to open the PR from there and not from any other fork.

I exchanged some messages with Strangelove and they are not pushing for an upstream PR yet. Even though they are getting very close to feature complete, they think they still more testing at all levels. So, even though I understand your point regarding visibility, I will defer the decision of when opening the PR to them, since I think they are in the best position to judge when they think they are ready.

> Would you mind letting me know what those changes are?

I think you already saw [one PR](https://github.com/strangelove-ventures/ibc-go/pull/17) that I had opened (got already merged) and after that one I opened [another one](https://github.com/strangelove-ventures/ibc-go/pull/21) (that's also merged now). Hopefully I will contribute with some more PRs in the next couple of weeks!

I hope this reasoning sounds reasonable!

**Pull request closed without merging**
