### PR TITLE
docs: final review of light client developer guide

### PR DESCRIPTION
**Pull request by tmsdkeys**
## Description

Final review of the light client developer docs. Made some corrections/changes:
- fixed order of `modules/core/exported` in a few instances
- moved `setup.md` to the end as it makes more sense imo
- combined the section on `ClientMessage` with the one one handling updates and misbehaviour as they respond to the `ClientMessage`, it looked cleaner
- moved `upgrade.md` before `proofs.md`
- Made `upgrade.md` easier to read by moving some text around and adding sections
- added some content in `proofs.md` as there was a circular referencing with `client-state.md`
- added a code block to `proposal.md`
- fixed the vuepress config as there was an incorrect ordering
- other stylistic changes performed by @crodriguezvega  

### Commit Message / Changelog Entry

```bash
docs: final review of light client developer guide
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [X] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [X] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing).
- [X] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [X] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by AdityaSripal — APPROVED** [review]
Nice cleanup!

**Comment by tmsdkeys** [comment]
Potential additional changes to consider:
- Now that we discuss upgrade handling for light client devs in the light client dev guide, we should likely remove it from the 'upgrades' section of the docs? Maybe just add a link...
- in `client-state.md` some methods in the interface are not listed. don't know is this is one purpose? `UpdateStateOnMisbehaviour`, `UpdateState`, `CheckSubstituteAndUpdateState` and `VerifyUpgradeAndUpdateState` are missing

**Review by damiannolan — APPROVED** [review]
Thanks @tmsdkeys! LGTM

**Comment by crodriguezvega** [comment]
> Potential additional changes to consider:
> 
> * Now that we discuss upgrade handling for light client devs in the light client dev guide, we should likely remove it from the 'upgrades' section of the docs? Maybe just add a link...

I removed the text that was there and added a link to the section.

> * in `client-state.md` some methods in the interface are not listed. don't know if this is on purpose? `UpdateStateOnMisbehaviour`, `UpdateState`, `CheckSubstituteAndUpdateState` and `VerifyUpgradeAndUpdateState` are missing

I added a comment in `client-state.md` to clarify that not all methods of the interface are listed there and some methods are explained in detail in other sections.

**Review by crodriguezvega — APPROVED** [review]
Great work, @tmsdkeys!

**Pull request merged**
