### PR TITLE
improvement: added module names in channel callback errors

### PR DESCRIPTION
**Pull request by alizahidraja**
## Description

Included Module names in channel callback errors

closes: #1728

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing) (does not apply, only updated error msg)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`) (does not apply, only updated error msg)
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by damiannolan — APPROVED** [review]
Thanks! 🙏 Nice improvement

**Review by crodriguezvega — COMMENTED** [review]
Thanks, @alizahidraja!

**Review by colin-axner — COMMENTED** [review]
Thanks @alizahidraja! Unfortunately with middleware, these error messages can be misleading. If we have a middleware stack which is ICS29 and ICS20, if ICS20 returns an error in the application callback, the final error message will actually indicate that the module which failed was fee-middleware (which is incorrect). 

I think it might make more sense to include the portID? We could also change the notion of the "module" variable to be a "middleware stack", though it'd be nice to think this approach out fully

**Comment by alizahidraja** [comment]
Thanks for the insights @colin-axner! Will update the code to cater for the issue mentioned

**Comment by alizahidraja** [comment]
Closing PR; Don't have access to the merging repo, will open a new one in the morning

**Comment by alizahidraja** [comment]
Continued [here](https://github.com/cosmos/ibc-go/pull/2399)

**Pull request closed without merging**
