### PR TITLE
ADR 010: IBC light clients as SDK modules

### PR DESCRIPTION
**Pull request by colin-axner**
## Description

**No solutions discussed in the ADR will be applied in the foreseeable future, the ADR is meant as documentation of a design discussion which can be referenced at a later time when the designs are easier to implement and immediately useful to many developers**

closes: #2782 

### Commit Message / Changelog Entry

```bash
imp: Add ADR 010, IBC light clients as SDK modules.
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by colin-axner** [comment]
@damiannolan @AdityaSripal could you push any discussion points I forgot to mention? 

Happy to let the team takeover this ADR while I am away, also fine if it sits

**Review by crodriguezvega — APPROVED** [review]

**Review by AdityaSripal — APPROVED** [review]
Could intermodule communication eventually be used for the channel level communication between core IBC and the applications?

**Comment by colin-axner** [comment]
> Could intermodule communication eventually be used for the channel level communication between core IBC and the applications?

Theoretically, I don't see why not. When a port is registered, it would just provide the module URL to route to messages expected to be supported (the IBC module interface). I haven't looked into much detail the exact proposed implementation (I think there's still a lot to nail down) so I'm not sure exactly how it would work

**Comment by colin-axner** [comment]
Going to merge, happy to receive any post merge reviews! :)

**Pull request merged**
