### PR TITLE
chore: write channel state before invoking app callbacks in ack and confirm channel handshake steps

### PR DESCRIPTION
**Pull request by damiannolan**
## Description

- Write channel state before app callbacks in `ACK` and `CONFIRM` handshake steps

closes: #2962

### Commit Message / Changelog Entry

```bash
chore(statemachine)!: write channel state before invoking app callbacks in ack and confirm channel handshake steps
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by chatton — COMMENTED** [review]
Change looks good to me, a few small things about the commit message, we technically don't have a category for `refactor`, however it will still work and be grouped correctly under a refactor section. 

I think we should not abbreviate `cbs` (even though it is the variable name in most cases) in the release notes.

I also think this is not a refactor, this is a change in behaviour because state is being written at different times, (correct me if I'm wrong!) I would be more included to count this is a `chore`, WDYT?

**Review by AdityaSripal — APPROVED** [review]
Ack

**Review by chatton — APPROVED** [review]
LGTM

**Comment by crodriguezvega** [comment]
Is this a state machine breaking change?

**Comment by damiannolan** [comment]
> Is this a state machine breaking change?

Good question and nice catch. I think given that we can't really assume what apps are doing in callback handlers (they may use channel state) then this would be considered state machine breaking. I can update the changelog

**Comment by crodriguezvega** [comment]
@chatton Do we still need a manual changelog entry for this PR for the backport to v4.3.x release branch?

**Comment by damiannolan** [comment]
Should we merge this PR @crodriguezvega? Do we need to backport to v5 and v6 also? 
I think we can handle putting changelogs in manually in mergify PRs if needs be, but I think they can be autogenerated too.

**Comment by chatton** [comment]
@crodriguezvega sorry I missed your question! 

If we backport this and preserve the commit message, when we generate the changelog on the other branch it should work okay.

**Comment by crodriguezvega** [comment]
> Should we merge this PR @crodriguezvega? Do we need to backport to v5 and v6 also?

We could backport as well to v5 and v6, although Confio is only interested in v4. Since v5 and v6 are based on SDK 0.46 and `x/wasm` seems like will upgrade to v7 directly from v4, then I am not sure if it's worth the effort, to be honest. This seems to be only needed for cosmwasm chains... I would say we don't backport for now and if we get a request for it, then we do it.

**Review by crodriguezvega — APPROVED** [review]

**Pull request merged**
