### PR TITLE
chore: add potential use cases documentation for ica 

### PR DESCRIPTION
**Pull request by colin-axner**
## Description

will fix ordering after #2561 is merged, so review that first

closes: #2472 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by damiannolan — COMMENTED** [review]
Awesome, thanks for picking this one up! I've added the Legacy API heading in my PR as you requested! :) 

Do you think its worth mentioning that controller side logic could be implemented entirely in a smart contract since it looks like we are going to include https://github.com/cosmos/ibc-go/issues/2580 in v6?

**Comment by colin-axner** [comment]
> Do you think its worth mentioning that controller side logic could be implemented entirely in a smart contract since it looks like we are going to include https://github.com/cosmos/ibc-go/issues/2580 in v6?

Personally I don't think so, I don't really think we should encourage folks to reimplement the controller module since it does do some essential logic

**Review by damiannolan — APPROVED** [review]
I think we can use relative links for the other doc pages. It will be more consistent if things change on main in future and we want to have v6 docs link to v6 specific stuff. I would expect these to change again after the legacy APIs are removed. 

Nice work 🚀

**Review by chatton — APPROVED** [review]
LGTM 👍

**Review by charleenfei — APPROVED** [review]
nice work!

**Pull request merged**
