### PR TITLE
feat(wip): add depinject support for app v2

### PR DESCRIPTION
**Pull request by crodriguezvega**
## Description

Still work in progress.

closes: #3560 

### Commit Message / Changelog Entry

```bash
imp: add depinject support for app v2
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by faddat** [comment]
Will you want to keep an appv1 app.go around?  

I've been thinking about this lots while writing the upgrade...

**Comment by faddat** [comment]
Well, it seems like v2 is going to be much easier to work with.  I suppose that if there are chains that wish to use appv1, then we should keep a simapp for them so that they can reference it.

That said, I've noticed a lot of the work that I'm doing is abstracted away by v2.  Should we open an issue?

**Comment by faddat** [comment]
Kinda vibing this way, too, though I think ideal is using both :/

Maybe we follow the SDK's lead:

* use v1 but we use go build tags to not use it by default
* use v2 by default

**Comment by crodriguezvega** [comment]
I think I have made some progress with this, but I am going to close this PR and open a new one.

**Pull request closed without merging**
