### PR TITLE
Remove circuit module

### PR DESCRIPTION
**Pull request by ikalyak**
## Description

closes: #7700

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by gjermundgaraba** [comment]
It would be helpful if you added some context on why you think the circuit module should be removed.

**Comment by ikalyak** [comment]
@gjermundgaraba hello, this https://github.com/cosmos/ibc-go/issues/7700

**Review by damiannolan — COMMENTED** [review]
Awesome thanks @ikalyak! Could you also remove it from the 08-wasm/testing/simapp?

I think we can keep it in the root ./simapp which we build docker images from in case its even needed for some e2e testing.

@gjermundgaraba the idea was to keep the simapp used for unit testing library as lightweight/trim as possible as circuit isn't a strict requirement for sdk apps. 
There may also be other modules that could be removed but I haven't gone through it in depth.

**Review by damiannolan — APPROVED** [review]
Thank you @ikalyak!

**Pull request merged**
