### PR TITLE
chore: update import paths for v8

### PR DESCRIPTION
**Pull request by faddat**
## Description

This PR updates the ibc-go import paths for v8

closes: #4377 

### Commit Message / Changelog Entry

```bash
type: update import paths for v8
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

- correct import paths
- update .proto files
- rebuild protobufs

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by faddat** [comment]
note: this will require getting interchaintest up to date with v8, because it imports v7's.

I suggest that we start a target branch @crodriguezvega

**Comment by faddat** [comment]
I'll make a PR into interchaintest that'll use these paths...

**Comment by crodriguezvega** [comment]
Yes, I think once we merge this PR bumping the package version we could then create the `release/v8.0.x` branch. We might want to wait a bit longer thought, so that we minimise the back ports for the PRs of the work that will go in v8, like the upgrade to SDK v0.50 of the gov v1 migration.

**Comment by faddat** [comment]
Will be better to re-create this after merging #4535

**Comment by crodriguezvega** [comment]
Thank you, @faddat, but closing the PR now as the work was done in https://github.com/cosmos/ibc-go/pull/4590.

**Pull request closed without merging**
