### PR TITLE
deps: upgrade to SDK 0.46-rc1

### PR DESCRIPTION
**Pull request by crodriguezvega**
## Description

SDK Middleware is out and ante handlers are back!

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by jackzampolin** [comment]
Whats the difference between this branch and this one https://github.com/cosmos/ibc-go/pull/1443

**Review by damiannolan — APPROVED** [review]
Looks good to me! 👍

**Comment by faddat** [comment]
I just want to confirm what this branch is or is not:

To the best of my knowledge, this branch is ibc-go v3.0.0 with sdk 46 rc1 and once the cosmos sdk v 46 makes a final release, this will be cut into some sort of tagged version, and then used on the Rho version of the cosmos hub?

**Comment by crodriguezvega** [comment]
> I just want to confirm what this branch is or is not:
> 
> To the best of my knowledge, this branch is ibc-go v3.0.0 with sdk 46 rc1 and once the cosmos sdk v 46 makes a final release, this will be cut into some sort of tagged version, and then used on the Rho version of the cosmos hub?
> 
> Can anyone please confirm if that is a correct understanding of intent here?

Yes, your understanding is correct. This is ibc-go v3.0.0 with SDK 0.46-rc1. The reason for this is:

- There are chain teams that are interested in having fee middleware with SDK 0.45.
- Cosmos Hub wants to roll out Rho upgrade with SDK 0.46, but not necessarily fee middleware. 

So we decided to give priority to making an official release first (i.e. ibc-go v4.0.0) to fee middleware with SDK 0.45. The Cosmos Hub team accepted to use a branch of ibc-go based on v3.0.0 and just with the changes required to upgrade to SDK 0.46.

Once we release v4.0.0, then we can make an official release with the upgrade of SDK 0.46 (I have at the moment the impression that it will most likely be v4.1.0, since I think there are not going to be any API breaking changes for the consumers of ibc-go).

**Comment by faddat** [comment]
Thank you very much for your explanation

**Pull request merged**
