### PR TITLE
override default docsBranch

### PR DESCRIPTION
**Pull request by crodriguezvega**
## Description

closes: #1354 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by colin-axner — COMMENTED** [review]
What does this do exactly?

**Comment by crodriguezvega** [comment]
> What does this do exactly?

Yeah, sorry, maybe I should have explained more. :) The problem is that the broken link mentioned in #1354 points to https://github.com/cosmos/ibc-go/edit/master/docs/README.md and there is no `master` branch in ibc-go, but `main`. So this PR is overriding the [default docs branch that is used in vuepress-theme-cosmos](https://github.com/cosmos/vuepress-theme-cosmos/blob/develop/layouts/GlobalLayout.vue#L367) to construct the URL.

**Review by colin-axner — APPROVED** [review]

**Comment by colin-axner** [comment]
Is it possible to make our docs website, by default, use the latest release instead of main. Just thinking using main docs might be confusing if there isn't a release yet

**Comment by crodriguezvega** [comment]
> Is it possible to make our docs website, by default, use the latest release instead of main. Just thinking using main docs might be confusing if there isn't a release yet

I would have to look into it, but maybe there could be a way. Would you like to open an issue?

**Pull request merged**
