### PR TITLE
Fix Wasm E2E Tests

### PR DESCRIPTION
**Pull request by chatton**
## Description

Marking as R4R to trigger E2Es.

This PR fixes the E2E wasm tests (with the exclusion of the MsgTransfer tests which fail due to ics20-v2)

The Setup logic is moved into SetupSuite and SetupTest, and the `ConfigureRelayer` fn is finally removed :partying_face: 

I added some additional log lines as debugging the hyperspace relayer was quite difficult due to it hanging rather than erroring.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by damiannolan — APPROVED** [review]
Approving, waiting for CI

**Comment by damiannolan** [comment]
image

Been looking at failing wasm e2es with @chatton. It looks to be the merkle path being encoded as base 64 bytes when the `SudoMsg` is passed to wasm.

**Comment by chatton** [comment]
> image
> 
> Been looking at failing wasm e2es with @chatton. It looks to be the merkle path being encoded as base 64 bytes when the `SudoMsg` is passed to wasm. This is due to #6633 and #6644 PRs

when running tests locally with older images these tests pass. We'll need to decide how to proceed with this breaking change

**Comment by damiannolan** [comment]
> oh, this is a contract api breaking change 👀

An attempt was made. https://github.com/cosmos/ibc-go/pull/6644/commits/733539ca62d6cff51d96356bcd098e45e65db2f4

**Comment by damiannolan** [comment]
Can we merge this so I can run tests on https://github.com/cosmos/ibc-go/pull/6644? or is there anything else left to do?

**Comment by chatton** [comment]
@damiannolan think we can merge  when ready, and can look into any failures after your PR gets merged after the fact

**Review by gjermundgaraba — APPROVED** [review]

**Pull request merged**
