### PR TITLE
chore: add wait time for packet relay to e2e test for ICA channel opening after packet timeout

### PR DESCRIPTION
**Pull request by charleenfei**
## Description

closes: #2850

I didn't add a changelog entry as as it didn't seem necessary.

### Commit Message / Changelog Entry

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by chatton — COMMENTED** [review]
I'm happy with this solution as it's in line with our other tests, but it might be worth considering doing something like

```golang
packetsRelayed := func() bool  { ... }
s.Eventually(packetsRelayed, timeoutAfter, pollingInterval, "failed to relay packets")
```

What do you think?

**Comment by colin-axner** [comment]
> What do you think?

I agree haha

**Comment by colin-axner** [comment]
I think ideally there would be a way we could call the relayer to clear all packets currently waiting to be relayed. I believe by the time `BroadcastMessages` returns, the packet send event should have already been relayed

**Comment by charleenfei** [comment]
> This is a good stop gap solution, but it'd be nice to add a function which could be certain to continue exactly when the packet has been relayed

I'll open an issue for this 👍

**Comment by chatton** [comment]
thanks for fixing the test @charleenfei  🥇 !

**Pull request merged**
