### PR TITLE
fix: allow value with slashes in URL template (for v4)

### PR DESCRIPTION
**Pull request by JoowonYun**
## Description

This is an issue that has already been raised and has been implemented in v7 and main. https://github.com/cosmos/ibc-go/pull/3045
This should also apply to v5 and v6, which are currently maintained, including v4.

closes: #XXXX

### Commit Message / Changelog Entry

```text
type: commit message
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by charleenfei** [comment]
thanks for this PR @JoowonYun! I will add the backport label.

**Review by charleenfei — APPROVED** [review]

**Comment by crodriguezvega** [comment]
Thanks, @JoowonYun. Considering that all lines of v4 and v5 will reach end of line at the end of October (see [here](https://github.com/cosmos/ibc-go/blob/main/RELEASES.md#ibc-go)), I question if it really makes a lot of sense to backport this fix to those lines? Have you encountered situations where this problem impeded you in chains using ibc-go < v7 and you couldn't work around the problem?

**Comment by charleenfei** [comment]
i actually think we might need to look into this more, finding [this issue](https://github.com/evmos/evmos/issues/1820). it looks like this fix actually introduced a bug in which the endpoint interprets an empty trace rather than a call to 
 the `DenomTraces` endpoint.

**Comment by crodriguezvega** [comment]
@JoowonYun I think the problem with `/ibc/apps/transfer/v1/denom_traces` that you may be having was fixed in https://github.com/cosmos/ibc-go/pull/4709. 

If this is causing you troubles and you cannot work around the issue, we are happy to backport both https://github.com/cosmos/ibc-go/pull/3045 and https://github.com/cosmos/ibc-go/pull/4709 to all currently supported release lines, we just wanted to make sure that we would cut all these releases for a good reason. :)

**Comment by JoowonYun** [comment]
Ah.. I didn't understand the backport process exactly. I checked the prs and it's perfect. 👍

**Comment by crodriguezvega** [comment]
@JoowonYun The [v4.5.1 release](https://github.com/cosmos/ibc-go/releases/tag/v4.5.1) with the fix is out now.

**Pull request closed without merging**
