### PR TITLE
47 sdk 47

### PR DESCRIPTION
**Pull request by faddat**
## Description

This PR begins integration work for cosmos-sdk 47 and will be developed in tandem with 

* https://github.com/cosmos/cosmos-sdk/issues/13408
* https://github.com/CosmWasm/wasmd/pull/1022
* https://github.com/cosmos/interchain-accounts-demo/pull/135

As before, this branch is meant for ecosystem devs to be able to reference.

This time, however, there is a clear order of events:

1) Upgrade ibc-go
2) Upgrade interchain accounts demo
3) Upgrade wasmd
4) Upgrade ethermint and evmos

### CODE REVIEW

**Comment by faddat** [comment]
Here's a PR to the SDK restoring the commit method in the SDK's tendermint client:

* https://github.com/cosmos/cosmos-sdk/pull/13482

**Comment by colin-axner** [comment]
Should we do the bump to ibc-go v7 last (after we bump to sdk v0.47). Would save on diffs?

**Comment by faddat** [comment]
Yeah, I can un-v7ify in a moment

**Comment by damiannolan** [comment]
Could we convert this to a draft while its still a work-in-progress? :)

**Pull request closed without merging**
