### PR TITLE
chore: change tendermint logging to debug for e2e

### PR DESCRIPTION
**Pull request by colin-axner**
## Description

This should hopefully give us more information when our e2e's fail

### Commit Message / Changelog Entry

```bash
chore: add support for tendermint debug log level
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by chatton — APPROVED** [review]
Nice LGTM!

**Review by damiannolan — APPROVED** [review]

**Comment by colin-axner** [comment]
After seeing how noisy the tm logs are, I'm wondering if maybe we should leave the code commented, so it can be easily enabled if we need to dig into the tendermint logs?

**Comment by damiannolan** [comment]
> After seeing how noisy the tm logs are, I'm wondering if maybe we should leave the code commented, so it can be easily enabled if we need to dig into the tendermint logs?

That sounds good to me. No need to use it as default behaviour if the logging is pretty heavy.

**Comment by colin-axner** [comment]
See https://github.com/cosmos/ibc-go/pull/3279/commits/b29c48ce38b85e1d92980dc11afedbccde5c8758, I left the other code as is as I think it is useful infrastructure to have for config overrides. Would appreciate followup reviews

**Review by charleenfei — APPROVED** [review]

**Comment by chatton** [comment]
> After seeing how noisy the tm logs are, I'm wondering if maybe we should leave the code commented, so it can be easily enabled if we need to dig into the tendermint logs?

This works for me, I can add this as an extra config field in #3260 to make it a single string we need to change.

**Review by chatton — APPROVED** [review]
ACK changes

**Pull request merged**
