### PR TITLE
Update error state on modules/core/04-channel/types/errors.go

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
## Description

closes: #4151

Hi [crodriguezvega](https://github.com/crodriguezvega),
just trying to fix this issue, please check it out

[Update error state on modules/core/04-channel/types/errors.go](https://github.com/cosmos/ibc-go/commit/8bb939d670b2c6bf32c4c487768af233a6029d27)

### Commit Message / Changelog Entry

```bash
type: commit message
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [X] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [X] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [X] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [X] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [X] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [X] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [X] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [X] Re-reviewed `Files changed` in the Github PR explorer.
- [X] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by DimitrisJim** [comment]
You'll get a lot of complaints from runners because references to this haven't been updated, see `grep -inr "ErrInvalidChannelState" . --include="*.go"`

Also,, we should either target the `04-channel-upgrades` branch or wait for it to get merged before merging this.

**Comment by viktoriussuwandi** [comment]
> You'll get a lot of complaints from runners because references to this haven't been updated, see `grep -inr "ErrInvalidChannelState" . --include="*.go"`
> 
> Also,, we should either target the `04-channel-upgrades` branch or wait for it to get merged before merging this.

@DimitrisJim @crodriguezvega 
To be honest, I don't know how to implement your idea.
Would you please let me know step by step how to do it ?

Appreciate your guidance

**Comment by crodriguezvega** [comment]
Hi @viktoriussuwandi, we just had a discussion about the issue for this PR and [decided to keep the name as is](https://github.com/cosmos/ibc-go/issues/4151#issuecomment-1647624124), so I will close this PR. I hope you don't mind. We appreciate that you opened a PR very quickly for it, and we are looking forward to our contributions from you. :)

**Comment by viktoriussuwandi** [comment]
Hi @crodriguezvega 

No problem
Thanks for your kindly response

**Pull request closed without merging**
