### PR TITLE
imp: adding `IsOpen` and `IsClosed` methods to Channel type (#4152)

### PR DESCRIPTION
**Pull request by AtreusSoltani**
## Description

Add IsOpen and IsClosed methods to Channel. 

closes: #4152

### Commit Message / Changelog Entry

```bash
imp: adding `IsOpen` and `IsClosed` methods to Channel type (#4152)
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [x] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by crodriguezvega — COMMENTED** [review]
Thanks, @AtreusSoltani. I think there a few more places where `IsClosed` could be used. If you look for `channel.State == types.CLOSED` you will find them. :)

**Comment by AtreusSoltani** [comment]
> Thanks, @AtreusSoltani. I think there a few more places where `IsClosed` could be used. If you look for `channel.State == types.CLOSED` you will find them. :)

You are right, I didn't see them before. I fixed it.

**Review by charleenfei — APPROVED** [review]
thank you @AtreusSoltani!

**Review by crodriguezvega — APPROVED** [review]
Looks good, thank you, @AtreusSoltani!

**Pull request merged**
