### PR TITLE
call packet.GetSequence() rather than passing the func as argument

### PR DESCRIPTION
**Pull request by joe-bowman**
## Description

Fixes incorrect param in logging on packet acknowledgement.

closes: #994 

Minor, no functional change.

### CODE REVIEW

**Review by crodriguezvega — APPROVED** [review]
Thank you, @joe-bowman!

**Review by colin-axner — APPROVED** [review]
Wow, nice catch. Thanks for pushing the fix!

**Review by AdityaSripal — APPROVED** [review]

**Review by seantking — APPROVED** [review]

**Comment by colin-axner** [comment]
@joe-bowman could you bring the branch up to date with main? Or give us privileges to do so? A changelog entry would also be wonderful

**Comment by crodriguezvega** [comment]
> @joe-bowman could you bring the branch up to date with main? Or give us privileges to do so? A changelog entry would also be wonderful

Hi @joe-bowman. If you have some time, it would be great if you could react on Colin's message above. Thanks in advance!

**Comment by joe-bowman** [comment]
> > @joe-bowman could you bring the branch up to date with main? Or give us privileges to do so? A changelog entry would also be wonderful
> 
> Hi @joe-bowman. If you have some time, it would be great if you could react on Colin's message above. Thanks in advance!

Done; apologies for the delay!

**Pull request merged**
