### PR TITLE
Use alpine as base image for building simd.

### PR DESCRIPTION
**Pull request by DimitrisJim**
## Description

Uses alpine as the base image. Size goes from 150mb to around 80ish.

closes: #2442

### Commit Message / Changelog Entry

```bash
chore: use alpine as base image in Dockerfile
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by DimitrisJim** [comment]
hm, might be a good idea to open this as a fork-pr since that should exercise the new docker image: https://github.com/cosmos/ibc-go/blob/4bb1b5101da975bb5e990742dd008357d64f4ed8/.github/workflows/e2e-fork.yml#L45

**Review by crodriguezvega — APPROVED** [review]
Looks good to me. Nice improvement, @DimitrisJim and @chatton!

**Review by charleenfei — APPROVED** [review]

**Comment by DimitrisJim** [comment]
though I'm pretty comfy with the state of this and the reviews, I'd definitely like it if @chatton you could also take a peek :eyes:

**Review by chatton — APPROVED** [review]
LGTM Thanks @DimitrisJim

**Pull request merged**
