### PR TITLE
fix: drop 32 bit arm support

### PR DESCRIPTION
**Pull request by faddat**
## Description

The "Tendermint in production" documentation states that we should not use 32 bit arm, or 32 bit CPUs generally.

https://docs.tendermint.com/v0.34/tendermint-core/running-in-production.html#validator-signing-on-32-bit-architectures-or-arm

### Commit Message / Changelog Entry

```bash
fix: drop 32 bit arm support
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by damiannolan — APPROVED** [review]

**Review by DimitrisJim — APPROVED** [review]
sdk does test against it, the main rationale for dropping it was 08-wasm and wasmVM which flat out doesn't support it, since that will be separate go mod though we could still keep it for ibc-go. Either way, fine with dropping it.

**Review by srdtrk — COMMENTED** [review]
I'm slightly in favour of closing this PR after hearing @DimitrisJim

**Comment by charleenfei** [comment]
thanks for this @faddat! but i guess I don't really see why keeping arm32 support in for our code/framework is necessarily a bad thing at this point, there hasn't been a huge increased overhead for our team i think. support just closing this PR!

**Comment by faddat** [comment]
Soooooo

+1 to @DimitrisJim -- I knew about this issue due to years of trying to run tendermint on raspberry pi while those were 32 bit or were 64 bit but had only 32 bit oses.

I suppose that if we can get a build running with 32 bit, then we are all set.  To my knowledge, we will run into arm and 32 bit issues with wasmvm in our stack now.

**Comment by srdtrk** [comment]
Closing for now since the SDK does test against it. Wasm is not a requirement for ibc-go. We can reopen if SDK stops testing against this or it causes us other problems.

**Pull request closed without merging**
