### PR TITLE
linting: use gci to sort imports

### PR DESCRIPTION
**Pull request by faddat**
## Description

This PR **only** adds gci to ibc-go, so that we can sort imports with ease. 

### Commit Message / Changelog Entry

```bash
chore: add gci to ibc-go
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by faddat** [comment]
Note:  I could refactor this in the same manner that I did the sdk, if desired:

https://github.com/cosmos/cosmos-sdk/pull/16605

**Review by crodriguezvega — APPROVED** [review]
I have to admit I haven't checked every single file, but I trust the linter to do its job. :)

Thank you, @faddat. It's nice to finally have a linter to end all import grouping/ordering wars. :D

I [updated the Go style guide to recommend readers to run `make lint-fix`](https://github.com/cosmos/ibc-go/pull/3887/files#diff-af74796481c3faa66a79d16e13a7682c42a9f40cb01c2d655daa3dc7e76a0409).

**Comment by crodriguezvega** [comment]
> Note: I could refactor this in the same manner that I did the sdk, if desired:
> 
> [cosmos/cosmos-sdk#16605](https://github.com/cosmos/cosmos-sdk/pull/16605)

I am personally not strongly opinionated: to me this grouping works fine. If others think some tweaking is needed, I will be also fine with it.

**Comment by faddat** [comment]
I'm good with either, as well :)

**Review by DimitrisJim — APPROVED** [review]
looks good to me

**Review by chatton — APPROVED** [review]
LGTM

**Review by Jonnyminac — CHANGES_REQUESTED** [review]
@crodriguezvega

**Pull request merged**
