### PR TITLE
Use generic `Contains` function in `03-connection`

### PR DESCRIPTION
**Pull request by pysel**
Closes: #3400

### CODE REVIEW

**Review by DimitrisJim — APPROVED** [review]
lgtm! thanks!

**Review by damiannolan — APPROVED** [review]
🙏

**Comment by DimitrisJim** [comment]
@pysel If you could merge main into your branch to get it up to date that would be great. If [you allow edits by maintainers,](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) we could do this too without you needing to merge manually.

**Comment by pysel** [comment]
@DimitrisJim, synced it

**Review by colin-axner — APPROVED** [review]

**Pull request merged**
