### PR TITLE
sdk for testnet-ibc

### PR DESCRIPTION
**Pull request by faddat**
This is a reference PR, not really for merging.  We need to make a testnet, since it is really hard to work against the existing testnets.

CONTAINS:

* a bump to the latest commit in cosmos-sdk v0.50.x branch
* all of the field length restrictions by @crodriguezvega (thank you!)
  * #4859  
* feat/wasm-clients and some approved PR's for feat/wasm-clients
* @julienrbrt's autocli enablement code (note: does this now need to be updated again?  it did not look like sdk's)

GOALS:

* for use in danger
* test sdk v0.50.x
* test comet v0.38.x
* test hermes and go-relayer on the 50 series and v8 series

### CODE REVIEW

**Comment by crodriguezvega** [comment]
@faddat Using this branch with the length checking in string fields, have you been able to verify if the issue does not happen anymore?

**Comment by faddat** [comment]
@crodriguezvega -- not yet, because it's for a testnet.

Going to make this into a testnet, code for the testnet is here:

* https://github.com/CosmWasm/wasmd/pull/1680

I did review the pull requests that you wrote, and the code looks sound.  I bet that it no longer happens.  But this testnet, called "danger zone" will be built different, it will be long-running and connect to other mainnets, and carry a warning label on it like a pack of cigarettes.  

So it is functionally speaking a mainnet.  This should help it to get validators.  Think of it as a mainnet that has no commercial plan and makes no promise at all of number go up, and could disappear tomorrow, for no reason, or for reason.

**Comment by crodriguezvega** [comment]
@faddat Do we still need this PR? Nothing from the PR is meant to be merged, right?

**Comment by faddat** [comment]
@crodriguezvega -- correct, I'm going to close it now :)

**Pull request closed without merging**
