### PR TITLE
feat: changes for ics

### PR DESCRIPTION
**Pull request by faddat**
## Description

This PR is part of an effort to support sdk 47 and ibc7 without forks.  We 
would love review and feedback, but it shouldn't be considered for merging 
at this time. 

It relates to this PR on ICS:

https://github.com/cosmos/interchain-security/pull/817

### Commit Message / Changelog Entry

pending. We don't even know if this should be merged, and the pr is being 
made so that we can get advice.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by crodriguezvega** [comment]
Thanks, @faddat. Could you please give us some more context/information of why this change would be needed?

If I look at https://github.com/cosmos/interchain-security/pull/817 and I see the item `Switch to forked vesion for ibc-go to bypass the passing of pointer to empty struct in IBCKeeper.NewKeeper`, does this mean that for ICS they need to be able to set a pointer to empty struct for the staking keeper? It sounds a bit strange to me that they would want that, so could you elaborate why that is needed?

**Comment by faddat** [comment]
I cannot, sorry.  @vuong177 can.  This needs to be linked to this:

https://github.com/cosmos/interchain-security/issues/852

and

https://github.com/cosmos/cosmos-sdk/pull/15917

**Comment by sontrinh16** [comment]
> 

hey yeah it weird please see the code lines in the link https://github.com/cosmos/interchain-security/blob/main/app/consumer/app.go#L317-L342. So we need the `consumerkeeper` to act as `stakingkeeper` in the consumer chain to pass in the `IBCKeeper`, while the `consumerkeeper` also need to pass in some properties of the `IBCKeeper` in order to do that IBCkeeper need to be initialize first. so to make this work they will pass the pointer to a empty struct first (`consumerkeeper`) then assign the value to where the pointer is pointed to. This use to work for ibc-go v4 since IBCKeeper only check for empty struct for stakingkeeper so in order for ics to work with ibc-go v7 we need to let the pointer to empty struct go throu

**Comment by faddat** [comment]
@crodriguezvega would this be better if it targeted main?

Also do you happen to see another way around it?

thank you.

**Comment by faddat** [comment]
@sontrinh16 I am going to make a pr that targets main, I think that the ibc-go team is preparing v8.0.0 right now.  I'll also leave this one open. @crodriguezvega thanks very much for your review.

**Comment by crodriguezvega** [comment]
Thanks for the explanations and the extra context, @sontrinh16 and @faddat. I see in the interchain-security repo that [an alternative approach is being followed for the upgrade to SDK 0.47 and ibc-go v7](https://github.com/cosmos/interchain-security/blob/d7e271fe1129eb307d47cafaa5abff3d75eadb35/app/consumer/app.go#L340-L357). Does that mean that we could close this PR?

**Comment by sontrinh16** [comment]
> Thanks for the explanations and the extra context, @sontrinh16 and @faddat. I see in the interchain-security repo that [an alternative approach is being followed for the upgrade to SDK 0.47 and ibc-go v7](https://github.com/cosmos/interchain-security/blob/d7e271fe1129eb307d47cafaa5abff3d75eadb35/app/consumer/app.go#L340-L357). Does that mean that we could close this PR?

yes i think we can closed this one

**Comment by crodriguezvega** [comment]
> yes i think we can close this one

Thank you for the quick reply, @sontrinh16!

**Pull request closed without merging**
