### PR TITLE
backport 583 to v1.1.x

### PR DESCRIPTION
**Pull request by crodriguezvega**
Backport #583.

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by seantking — APPROVED** [review]

**Review by colin-axner — APPROVED** [review]

**Comment by colin-axner** [comment]
Hmm, this pr seems to be missing the `.pb.go` changes (which is what fixes the issue at hand)

**Comment by crodriguezvega** [comment]
> Hmm, this pr seems to be missing the `.pb.go` changes (which is what fixes the issue at hand)

Hmm, the previous PR had those changes and it was not building, so I thought that they were not needed for v1.x... Ok, I guess the release will not go out today then until we figure this out...

**Comment by seantking** [comment]
> > Hmm, this pr seems to be missing the `.pb.go` changes (which is what fixes the issue at hand)
> 
> Hmm, the previous PR had those changes and it was not building, so I thought that they were not needed for v1.x... Ok, I guess the release will not go out today then until we figure this out...
> 
> This is the error I got:
> 
> ```
> modules/light-clients/07-tendermint/types/tendermint.pb.go:9:2: cannot find module providing package github.com/cosmos/ibc-go/v2/modules/core/02-client/types: import lookup disabled by -mod=readonly
> modules/light-clients/07-tendermint/types/tendermint.pb.go:10:2: cannot find module providing package github.com/cosmos/ibc-go/v2/modules/core/23-commitment/types: import lookup disabled by -mod=readonly
> make: *** [build] Error 1
> ```
> 
> I thought that maybe because the proto files were generated using the v2 that's why it was causing issues in the v1.x branches...
> 
> Is the solution to run `make proto-gen` again to regenerate the pb.go files?
> 
> cc: @marbar3778

I had the same issue on the `interchain-accounts` repo when I took the latest changes from main. I set the `buf.yaml` to just ignore the files that have issues. Seems like linting is failing anyway.

**Comment by marbar3778** [comment]
not sure why the pb.go files are missing, but running `go mod tidy` may fix this

**Comment by crodriguezvega** [comment]
This is the [PR](https://github.com/cosmos/ibc-go/pull/586) I opened with the pb.go changes from main, but then it was not building, so I thought I made a mistake during the backport and closed that PR and opened this one without those changes...

**Review by jackzampolin — APPROVED** [review]

**Comment by colin-axner** [comment]
> Is the solution to run `make proto-gen` again to regenerate the pb.go files?

Correct. This worked for me on this branch

**Comment by crodriguezvega** [comment]
> > Is the solution to run `make proto-gen` again to regenerate the pb.go files?
> 
> Correct. This worked for me on this branch

Thanks, @colin-axner. Will do that!

**Review by colin-axner — APPROVED** [review]
ACK .pb.go changes

**Pull request merged**
