### PR TITLE
test: refactor used expected errors

### PR DESCRIPTION
**Pull request by hoank101**
## Description

closes: #6214

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

## Summary by CodeRabbit

- **Tests**
	- Enhanced the `TestOnChanOpenInit` to improve error handling by using specific error types instead of boolean values, refining test validation processes.

### CODE REVIEW

**Review by damiannolan — APPROVED** [review]
Thank you!

**Review by crodriguezvega — COMMENTED** [review]
Thanks, @hoank101. This PR would partially address https://github.com/cosmos/ibc-go/issues/6214. Do you plan to refactor the rest of the tests in this file in follow-up PRs?

**Comment by hoank101** [comment]
> Thanks, @hoank101. This PR would partially address #6214. Do you plan to refactor the rest of the tests in this file in follow-up PRs?

thank you for feedback, I updated

**Review by colin-axner — APPROVED** [review]
Thank you @hoank101! That was really fast. Great improvement!

**Review by damiannolan — APPROVED** [review]
ACK updates! Many thanks 🙏

**Review by crodriguezvega — APPROVED** [review]
Much appreciated the speedy update of the PR, @hoank101 🙏

**Pull request merged**
