### PR TITLE
Cleanup intertx e2e tests 

### PR DESCRIPTION
**Pull request by chatton**
## Description

closes: #4592

This PR:
- Removes all references to intertx in tests.
- Removes the specification of `chain-image` and `chain-binary` from the compat tests. (these were only required so we could pass icad)
- Remove icad references in READMEs.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by damiannolan — APPROVED** [review]
🚀 🚀 🚀 🔥 🔥 🔥 🥇

**Review by charleenfei — APPROVED** [review]
it's the end of an era 🔥

**Comment by crodriguezvega** [comment]
🪦💀
image

**Comment by colin-axner** [comment]
https://github.com/cosmos/ibc-go/assets/25233464/e9f53983-123b-4c50-8356-f1a913e834f9

**Comment by chatton** [comment]
I broke upgrade tests somehow! Will fix before I merge

**Pull request merged**
