### PR TITLE
docs: fix broken link `adr-008-app-caller-cbs.md`

### PR DESCRIPTION
**Pull request by kienn6034**
## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by DimitrisJim** [comment]
is this an actual broken link? I seem to be able to access it? (ref https://ibc.cosmos.network/architecture/adr-008-app-caller-cbs/)
maybe `.md` is assumed suffix?

**Comment by kienn6034** [comment]
@DimitrisJim when i navigate around the code (vs-code), it seems does not work. 

if it is not intended behavior, i think we can close the PR 

thanks for reviewing anw

**Comment by damiannolan** [comment]
Within the context of the github repository I think the link is probably fine and works correctly. I think if you're navigating using your local dev env then it may attempt to take you to the root of your filesystem and then it is sad. 

We can change if you want ¯\_(ツ)_/¯ I don't feel strongly

**Review by damiannolan — APPROVED** [review]
I think as a general rule of thumb its better to use relative links in docs than absolute 👍🏻

**Comment by gjermundgaraba** [comment]
Since the links work, I'll close this for now :)

**Pull request closed without merging**
