### PR TITLE
Removed memkey from ICA keeper

### PR DESCRIPTION
**Pull request by lukerhoads**
## Description

Removed `memKey` from ICA keeper.

closes: #336

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by crodriguezvega — APPROVED** [review]
Thanks for this PR, @lukerhoads!

**Review by colin-axner — APPROVED** [review]
Great work, thanks!

**Comment by colin-axner** [comment]
Looks like the tests are failing. The call to the interchain accounts `NewKeeper` in `testing/simapp/app.go` needs to be fixed. You should be able to run `make test` at the top level of this repository to test changes locally

**Comment by lukerhoads** [comment]
The reason these tests are failing is beyond me... its some access denied another resource is using error in the `Failing IBC Message` case section of the `sdk_test.go` file in testing. Probably some issue with me being on windows.

**Comment by colin-axner** [comment]
Looks like tests are passing, thanks! I'm guessing the `sdk_test.go` issue has something to do with your local setup

**Pull request merged**
