### PR TITLE
use controller module address instead of module name for NewMsgChannelOpenInit

### PR DESCRIPTION
**Pull request by catShaark**
## Description

In controller keeper's `registerInterchainAccount` we execute a `MsgChannelOpenInit` to set up an ica channel. Currently, we have [`icatypes.ModuleName`](https://github.com/cosmos/ibc-go/blob/95cec44c9fb10a2e84a327cdd98c7d588f091f42/modules/apps/27-interchain-accounts/controller/keeper/account.go#L63) as the msg signer. This is not good because the [`ValidateBasic()`](https://github.com/cosmos/ibc-go/blob/692790402a033c1d9647c1e1eded5351332283bf/modules/core/04-channel/types/msgs.go#L34) of `MsgChannelOpenInit` has check if msg signer is bech32 or not.

ref #2566

closes: #2559

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by faddat** [comment]
Hey great work

**Comment by faddat** [comment]
Let's keep this open and please also merge it into the other one We can see if it completes it

**Comment by catShaark** [comment]
> Let's keep this open and ready to merge and please also merge it into the other one for 0.46.* and see if that passes CI.
> 
> Also the update to tests that Carlos made might be relevant here

I've already checked this with the new sdk46, we have all the tests passed

**Review by damiannolan — CHANGES_REQUESTED** [review]
Hey, thanks for this. 

We can avoid making this an API breaking change by using [authtypes.NewModuleAddress(...)](https://github.com/cosmos/cosmos-sdk/blob/main/x/auth/types/account.go#L164) and avoid having to depend on the auth keeper directly.

**Comment by crodriguezvega** [comment]
Thanks for fixing this, @catShaark!

@colin-axner @damiannolan Can you please check that the backport labels are correct? I guess that the we will have to do some manual work for the backports to < v6.0.x...

**Comment by faddat** [comment]
hey, I'll ping Mr. Shaark now.  I would not know quite how to clean this one.

**Comment by catShaark** [comment]
@damiannolan , I've applied your suggestion like you said, can you check?

**Comment by faddat** [comment]
hi, ibc-go team, please know that I just tried to use this and more or less-- not a chance that this will cleanly backport. 

Suggest that backport labels are removed, Mr. Shaark gets some sleep, and we go branch by branch.

**Comment by yihuang** [comment]
Please backport to v5.0

**Review by colin-axner — APPROVED** [review]
Thanks @catShaark, sorry for the delayed review. Can you fix the imports, then we are good to merge. I'm going to tag the backport labels anyways, we can close the pr's if the merge isn't clean

**Review by damiannolan — APPROVED** [review]
Thanks for applying the suggestion! LGTM 🚀

**Review by AdityaSripal — APPROVED** [review]

**Comment by faddat** [comment]
* https://github.com/cosmos/ibc-go/pull/2582

So, I don't think this backports cleanly.  @yihuang there's the v5 one

**Pull request merged**
