### PR TITLE
enable mergify for backports

### PR DESCRIPTION
**Pull request by crodriguezvega**
## Description

closes: #677

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by fedekunze — APPROVED** [review]
ACK! not sure if the file your go on the github/ folder tho

**Comment by crodriguezvega** [comment]
> ACK! not sure if the file your go on the github/ folder tho

Yes, I saw that in the [documentation](https://docs.mergify.com/getting-started/#the-configuration-file) and [Tendermint does the same thing.](https://github.com/tendermint/tendermint/blob/master/.github/mergify.yml)

**Review by damiannolan — APPROVED** [review]

**Comment by fedekunze** [comment]
@Mergifyio backport release/v3.0.x

**Comment by fedekunze** [comment]
Hmm not sure what's going on...

**Comment by crodriguezvega** [comment]
> Hmm not sure what's going on...

Looks like it's still not enabled... At least this repository doesn't show up in the mergify dashboard. I will check with Marko.

**Pull request merged**
