### PR TITLE
fix: fixed callbacks middleware wiring

### PR DESCRIPTION
**Pull request by srdtrk**
## Description

closes: #5945

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [x] Updated relevant documentation (`docs/`).
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

## Summary by CodeRabbit

- **Documentation**
	- Updated middleware integration documentation for IBC module, including adjustments to middleware stack order and configuration.
- **New Features**
	- Introduced `GetICS4Wrapper` method across various modules for consistent ICS4 wrapper retrieval.
	- Added transfer memo functionality in callbacks for enhanced testing scenarios.
- **Refactor**
	- Refactored `Keeper` structures in interchain accounts and fee modules for improved clarity and functionality.
	- Updated test cases to reflect new callback functionalities and middleware configurations.
- **Bug Fixes**
	- Fixed middleware call order in simulation app to ensure correct middleware stacking.
- **Chores**
	- Removed unused `GetICS4Wrapper` functions and import statements to clean up the codebase.

### CODE REVIEW

**Review by AdityaSripal — APPROVED** [review]
Nice work!

**Review by damiannolan — APPROVED** [review]
Awesome! Nice one @srdtrk ❤️ 

Agree with the point on more verbose docs, but such is life with the app wrapping at the moment. Looking forward to when we have a alternative solution :)

**Review by crodriguezvega — APPROVED** [review]
Thanks for fixing this, @srdtrk. Do we need to backport this to v0.2.x release branches of callbacks? Just to keep code in sync with main to prevent conflicts down the road...

**Comment by srdtrk** [comment]
@crodriguezvega back-porting seems like a good idea

**Pull request merged**
