### PR TITLE
constructors to create wasm contract call json payloads

### PR DESCRIPTION
**Pull request by Reecepbcups**
## Description

Moves verifyMembership and verifyNonMembership types into their respective constructor functions for cleaner (1q line) payload generation.

closes: #4044

### Commit Message / Changelog Entry

```bash
type: commit message
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by crodriguezvega** [comment]
Thank you for picking up a bunch of the 08-wasm issues, @Reecepbcups. :) This one in particular will require some changes, since we received a recommendation by Ethan Frey to organise the payload types a bit differently. I will open an issue and post it here when it's ready.

**Comment by Reecepbcups** [comment]
np, sounds good

**Comment by damiannolan** [comment]
These structs will be replaced with two higher level structures for `Sudo` and `Query` contract calls with each containing a pointer to a struct to represent each action, note the `omit_empty` is required for json serialization. These structures play well with having the msg enums defined in the rust code for match expressions etc:

```go
// encapsulates read-only contract calls
type QueryPayload struct {
  MsgStatus *StatusPayload `json:"msg_status,omitempty"`
  MsgVerifyMembership *VerifyMembershipPayload`json:"msg_verify_membership,omitempty"`
  // ..etc
}

// anything which writes to store
type SudoPayload struct {
  MsgInitialize *InitializePayload `json:"msg_initialize,omitempty"`
  MsgUpdateState *UpdateStatePayload `json:"msg_update_state,omitempty"`
  // ..etc
}
```

**Comment by crodriguezvega** [comment]
Hi @Reecepbcups, this [PR](https://github.com/cosmos/ibc-go/pull/4133) implements the changes mentioned by @damiannolan above. Take a look and let us know if you would like to continue the work of your PR. If you're busy, no problem, we can take over :) Also, it might be better to use the branch of #4133 to implement the changes on top of it.

**Comment by Reecepbcups** [comment]
@crodriguezvega Hey sorry for the late reply here. I will be out of town the next 7 - 10ish days so I will not be able to take this on.

I will get to more cleanup PRs once I get back if this has not been handled by then. (+ older issues I find)

**Pull request closed without merging**
