### PR TITLE
Replace initialization with declaration in grpc query handlers

### PR DESCRIPTION
**Pull request by expertdicer**
## Description

closes: #3376

### Commit Message / Changelog Entry

```bash
nit: Replace initialization with declaration in grpc query handlers
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by DimitrisJim** [comment]
thanks! Be prepared for some tests maybe failing since they sometimes assert that nothing has been returned (which now will be different because tests have been written to expect an empty slice and not a nul slice).

I.e you might need to tweak some of the tests too.

**Comment by expertdicer** [comment]
> thanks! Be prepared for some tests maybe failing since they sometimes assert that nothing has been returned (which now will be different because tests have been written to expect an empty slice and not a nil slice).
> 
> I.e you might need to tweak some of the tests too.

Lmao. I will be

**Comment by DimitrisJim** [comment]
Nice! I did not originally do an exhaustive search but _trying_ one now does seem to find an additional instance in the query for `DenomTraces`:

https://github.com/cosmos/ibc-go/blob/2632ae24926e251fb70efabaa1a8b92755c7bccc/modules/apps/transfer/keeper/grpc_query.go#L53

I'm not able to grep for any other instance, hopefully this is the last of em.

**Review by DimitrisJim — APPROVED** [review]
lgtm, thanks @expertdicer!

**Review by crodriguezvega — APPROVED** [review]

**Comment by damiannolan** [comment]
Hey @expertdicer I think you'll need to resync the branch with main. It may be easier to work off a personal fork and use the "Allow edits from maintainers" checkbox. That would allow us to handle cases like this and speed up PRs being merged :) 

Thanks for all your contributions lately ❤️

**Review by colin-axner — APPROVED** [review]

**Comment by colin-axner** [comment]
Looks like there was a merge conflict

**Review by damiannolan — APPROVED** [review]
Thanks again @expertdicer ❤️ 🙏

**Pull request merged**
