### PR TITLE
add check send enabled

### PR DESCRIPTION
**Pull request by crodriguezvega**
## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by damiannolan — APPROVED** [review]
Thanks @crodriguezvega 🙏

**Comment by yihuang** [comment]
Hi, could you backport this to `v5.0.x`? we are using that version.

**Comment by colin-axner** [comment]
> Hi, could you backport this to `v5.0.x`? we are using that version.

Hi, this change is state machine breaking. It will be included in v5.1, can you upgrade to that?

**Comment by yihuang** [comment]
> > Hi, could you backport this to `v5.0.x`? we are using that version.
> 
> Hi, this change is state machine breaking. It will be included in v5.1, can you upgrade to that?

state machine breaking, I see, thanks.

**Comment by colin-axner** [comment]
v5.1.0 is available https://github.com/cosmos/ibc-go/releases/tag/v5.1.0, thanks for your patience

**Pull request merged**
