### PR TITLE
bump go package to v2

### PR DESCRIPTION
**Pull request by colin-axner**
## Description

closes: #389 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [x] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by damiannolan — APPROVED** [review]

**Review by seantking — APPROVED** [review]

**Comment by marbar3778** [comment]
What is the upgrade path for this?

**Review by AdityaSripal — APPROVED** [review]

**Comment by colin-axner** [comment]
> What is the upgrade path for this?

#401 updates the migration docs outlining the required changes based on user group. As it stands right now, all deps would need to do import changes and IBC applications need to support a new interface function. No migrations required, but the changes included are state machine breaking and require a coordinated upgrade

**Comment by marbar3778** [comment]
Will relayers have to upgrade, or is it backwards compatible?

**Comment by colin-axner** [comment]
> Will relayers have to upgrade, or is it backwards compatible?

A final release won't be done until we are certain Hermes and the ts-relayer work fine. The only issue that might need to be addressed is their support for > uint64 amounts, otherwise ibc-go v2 supports IBC spec v1. For more information checkout #408

**Pull request merged**
