### PR TITLE
imp(02-client,03-connection)!: remove `ValidateSelfClient`

### PR DESCRIPTION
**Pull request by srdtrk**
## Description

This addresses the spec changes proposed in https://github.com/cosmos/ibc/issues/1121

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to GitHub issue with discussion and accepted design, OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [conventional commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to follow the repository standards.
- [ ] Include a descriptive changelog entry when appropriate. This may be left to the discretion of the PR reviewers. (e.g. chores should be omitted from changelog)
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Review `SonarCloud Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by srdtrk** [comment]
Yes @damiannolan. I didn't wanna have too much diff in a single PR. Plus, I didn't wanna deal with any potential side-effects in this PR.

**Comment by srdtrk** [comment]
Would everyone prefer me to do this here?

**Review by damiannolan — APPROVED** [review]

**Comment by damiannolan** [comment]
> Would everyone prefer me to do this here?

Fine with doing it in two steps. Hopefully the next one doesn't cause any hassle!

**Review by crodriguezvega — COMMENTED** [review]
Thanks, @srdtrk. So just to confirm: we want to release these changes already in v9, right?

We should add a changelog and also update the migration docs, with the removal of `ValidateSelfClient` function in 02-client keeper and the removal of `ConsensusHost` interface (since that was introduced in v8.3).

**Review by colin-axner — APPROVED** [review]
ACK changes, but would like to hold off merging until we get the analysis from @AdityaSripal. Maybe we can have a feat branch in the meantime?

**Comment by crodriguezvega** [comment]
I will restrain from adding the backport label until we are given the green light to merge!

**Review by gjermundgaraba — APPROVED** [review]

**Comment by srdtrk** [comment]
Merged to a feature branch

**Pull request merged**
