### PR TITLE
chore: v4->v5 only

### LINKED ISSUE #1780: Bump package to v5
We are going to release the upgrade to SDK 0.46 as v5, and since it contains API breaking changes and we follow go semantic versioning, then we need to bump our package. The go.mod file will read:

module github.com/cosmos/ibc-go/v5

All imports will need to change.

### PR DESCRIPTION
**Pull request by faddat**
## Description

This PR **only** changes module paths from v4 to v5.

It'll make #1653 much easier to review.

Closes #1780 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by chatton** [comment]
Hi @faddat thanks for this, it's looking great!

Can we leave everything under the `e2e` directory at `v4` though? For the same reason outlined in the other PR.

**Comment by faddat** [comment]
yep, I was wondering about that.  Fixing :)

**Review by damiannolan — CHANGES_REQUESTED** [review]
Thanks @faddat, much appreciated! ❤️ 

Could you update the protobuf `go_package` option also to reflect the `v5` module naming? You can run `make proto-all` to regenerate the `.pb.go` files with the appropriate import path then!

**Comment by faddat** [comment]
fixing the fix...

**Comment by faddat** [comment]
so, I think there's something wrong with make proto-gen

new .pb.go files are being made but not being used.

**Review by crodriguezvega — APPROVED** [review]
Thanks so much, @faddat!

**Review by damiannolan — APPROVED** [review]

**Review by colin-axner — APPROVED** [review]
:rocket:

**Pull request merged**
