### PR TITLE
chore: rename any var to protoAny

### PR DESCRIPTION
**Pull request by RegisGraptin**
## Description

Some variable names are too generic and are not precise in the code. This is the case with some variables named `any`. A change has been made to rename it `protoAny` instead.

This modification has been made on the variable names when they were assigned by the functions `codectypes.NewAnyWithValue()` or `clienttypes.PackClientState()`. It was partially changed on a [previous merge](https://github.com/cosmos/ibc-go/pull/2824/files#r1040714332). I do not know if other parts of the code needed to be changed ? Nor the documentation ?

closes: #2890

### Commit Message / Changelog Entry

```bash
chore: rename any var to protoAny
```

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting)).
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [x] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by RegisGraptin** [comment]
Hey @damiannolan,

Thanks for your reply.
Okay, I will take a look at the other tuples of variables named `any, err` and modify it. And have a look on other variables with only `any`.
I didn't know if all the `any` variables needed to be modified, as they might need to be named differently depending on the function called (maybe not `protoAny` but something else).

**Comment by crodriguezvega** [comment]
> Do we need to standardized the naming convention for those two ?

I would say let's just use the same name (`protonAny`) everywhere. We can add this to our coding style guide.

**Comment by crodriguezvega** [comment]
Thanks for the latest updates, @RegisGraptin. Do you think the PR is now ready for review?

**Comment by RegisGraptin** [comment]
Hey @crodriguezvega. Yes, I think it should be good :)

**Review by damiannolan — APPROVED** [review]
Thanks for the contribution! ❤️

**Review by colin-axner — APPROVED** [review]
Thank you @RegisGraptin! Appreciate the time you took to fix this for us!

**Pull request merged**
