### PR TITLE
 Remove unnecessary event attribute from INIT Handshake Msgs 

### PR DESCRIPTION
**Pull request by ruthishvitwit**
## Description

closes: #3847

### Commit Message / Changelog Entry
Removed counterparty connection/channel id from both ConnOpenInit and ChanOpenInit as they will both be empty in this stage 
```bash
chore(api)!: Remove unnecessary event attribute from INIT Handshake Msgs
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by crodriguezvega — COMMENTED** [review]
Thank you for this PR, @ruthishvitwit!

From a quick look at relayer and Hermes code, it looks like it should be safe to remove these from the events.

Relevant links for relayer: [this](https://github.com/cosmos/relayer/blob/0981e674fae2d1d2cc3ed8f2501fee7a851d3062/relayer/chains/cosmos/event_parser.go#L414) and [this](https://github.com/cosmos/relayer/blob/0981e674fae2d1d2cc3ed8f2501fee7a851d3062/relayer/chains/cosmos/event_parser.go#L382). If the key is not present in the event, then the parser will just not try to parse the value and it will default to empty string anyway. Besides, the e2e tests are passing in your PR, so that's also a good sign.

Relevant links for hermes: [this](https://github.com/informalsystems/hermes/blob/16710570b85bde99e9f02f0b66c3d95c5f028a1e/crates/relayer/src/event.rs#L356) and [this](https://github.com/informalsystems/hermes/blob/16710570b85bde99e9f02f0b66c3d95c5f028a1e/crates/relayer/src/event.rs#L391). Similar thing as with relayer: if the key is not present then the value will be a `None`, instead of an `Some("")`, but that should be fine too.

Mentioning here @jtieri and @ljoss17 for extra confirmation.

Maybe it would be nice also to mention this change in the `v7-to-v8` migration docs.

**Comment by ljoss17** [comment]
Everything looks good on Hermes side, I ran the tests and haven't seen any issues with the changes from this PR

**Review by crodriguezvega — APPROVED** [review]
Thank you, @ruthishvitwit! Given that e2e tests use golang relayer and they pass, it should be fine with it.

**Review by DimitrisJim — APPROVED** [review]
thanks @ruthishvitwit :partying_face:

**Pull request merged**
