### PR TITLE
testing: e2e support for sdkv50

### PR DESCRIPTION
**Pull request by charleenfei**
## Description

adds e2e support for sdkv50

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by colin-axner** [comment]
After the interchain team debugged the e2e's, we found two required updates from the go relayer for all e2e's to pass:
- https://github.com/cosmos/relayer/issues/1272 (short term fix available)
- https://github.com/cosmos/relayer/issues/1273 (requires help to devise a fix)

I guess we will need to wait until we get a new docker image that fixes the interchain account gov integration test

**Comment by faddat** [comment]
@colin-axner you're right about that nit.  I doubled up the C at some point and uh, that's how we got that.

**Review by colin-axner — APPROVED** [review]
AAAAAmaazing!!!! :1st_place_medal:

**Review by damiannolan — APPROVED** [review]
Green lights 🟢 LGTM!

**Pull request merged**
