### PR TITLE
adding markdown link checker to CI workflows

### PR DESCRIPTION
**Pull request by damiannolan**
## Description

- adding markdown link checker to CI workflows

closes: #253 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by seantking — APPROVED** [review]
Approved :+1:

**Comment by damiannolan** [comment]
Looks like there's quite a few dead links being flagged. 
These can either be addressed in a follow up PR or I can make this a draft and start correcting them.

**Comment by seantking** [comment]
> Looks like there's quite a few dead links being flagged.
> These can either be addressed in a follow up PR or I can make this a draft and start correcting them.

I would leave this decision to @colin-axner. I guess the only problem with follow-up PRs is seeing some checks fail in the meantime. 

IMO we can merge it in and the failed checks will remind us to clean up in future :shrug:

**Review by colin-axner — APPROVED** [review]
ACK - I'm fine merging as well, but we should open an issue and try to fix these as soon as we can

**Comment by damiannolan** [comment]
> ACK - I'm fine merging as well, but we should open an issue and try to fix these as soon as we can

Created #381 👍

**Pull request merged**
