### PR TITLE
Update proto dependencies

### PR DESCRIPTION
**Pull request by faddat**
## Description

I think this really needs to target just one branch.  It is not yet done. 

### Commit Message / Changelog Entry

```bash
type: commit message
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by crodriguezvega** [comment]
Hey @faddat, thanks for the PR. Do you think this is still needed?

**Comment by damiannolan** [comment]
> Hey @faddat, thanks for the PR. Do you think this is still needed?

The updated protos don't produce any changes to our codegen after `make proto-all`. But I think it would be good to merge this PR personally. I always found the manual proto dependency management via makefile getting stale, its nice to have Buf now but would be good to have the v4 release branch properly up to date imo!

**Comment by faddat** [comment]
Guys I forgot all about this one but I will try and get it back and rolling in the next couple of days

**Comment by crodriguezvega** [comment]
@faddat, you think you still have time to push this to the finish line?

**Comment by colin-axner** [comment]
marking as draft because minor adjustments are needed, I believe @crodriguezvega will address any required changes

**Review by damiannolan — APPROVED** [review]

**Review by DimitrisJim — APPROVED** [review]

**Review by colin-axner — APPROVED** [review]

**Pull request merged**
