### PR TITLE
fix e2e ica tests

### PR DESCRIPTION
**Pull request by crodriguezvega**
## Description

I wonder how the e2e tests passed for #2607...

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by damiannolan — APPROVED** [review]

**Review by chatton — APPROVED** [review]
It looks like tests didn't actually pass for #2607 it was a mistake on our end to have it merged! (we don't block on e2e atm)

**Comment by colin-axner** [comment]
> It looks like tests didn't actually pass for #2607 it was a mistake on our end to have it merged! (we don't block on e2e atm)

yea my bad! I'd like to block on end to end's failing but sometimes they fail undeterministically  Maybe we could give it a try anyways

**Comment by chatton** [comment]
> yea my bad! I'd like to block on end to end's failing but sometimes they fail undeterministically Maybe we could give it a try anyways

My estimate would be around 2-3% of tests seem to fail the first time around due to some sort of test setup-failure. I think we could definitely try blocking on it, but I don't want to add additional hoops for devs to jump through with manual retries.

But actually, building the e2e tests is a requirement, ([or at least it was intended to be](https://github.com/cosmos/ibc-go/blob/57e518cf21b3b3134562c89718622c435ceefe91/.github/workflows/test.yml#L54-L55)) so that should catch this sort of error. Maybe since we split it up into separate packages it no longer works as expected.

**Comment by colin-axner** [comment]
I agree. So the plan is to ensure build failures block merge, then maybe if we get inconsistent failure rate down, we can block on tests passing?

**Comment by chatton** [comment]
@colin-axner yep exactly that.

**Pull request merged**
