### PR TITLE
Fix error in Code Coverage workflow

### PR DESCRIPTION
**Pull request by chatton**
## Description

When the e2e tests were introduced, the e2e tests were excluded from the unit tests in an incorrect fashion, which resulted in each task running *all* tests as opposed to splitting up the tests into 4 sections.

The workflow will be skipped on this PR as no go files are changed. See the [this workflow](https://github.com/cosmos/ibc-go/actions/runs/3046209446/jobs/4908745499) which ran with the changes to see the run times.

closes: #2167

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Review by crodriguezvega — COMMENTED** [review]
Awesome, @chatton! I guess this also fixes [this issue](https://github.com/cosmos/ibc-go/issues/2167)?

**Comment by chatton** [comment]
@crodriguezvega yes it looks like a duplicate issue, I've closed the original and updated the closes in the description! Thanks for pointing it out.

**Review by damiannolan — APPROVED** [review]
Nice! 🙏

**Review by colin-axner — APPROVED** [review]
Excellent catch! You are the man!

**Pull request merged**
