### PR TITLE
feat: adding connection params grpc and cli query

### PR DESCRIPTION
**Pull request by damiannolan**
## Description

- Rename query `Params` to `ClientParams` to avoid naming collisions
- Adding `ConnectionParams` grpc and cli query
- Adding missing top level wiring for client query `UpgradedConsensusState`

closes: #2069 

### Commit / Changelog

```
imp: (core/03-connection) Adding `ConnectionParams` grpc query and CLI to 03-connection.
fix: (modules/core/keeper) Fix request wiring for `UpgradedConsensusState` in core query server.
```

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by damiannolan** [comment]
Note this undos the changes from #2573 in order to avoid naming collisions. We can keep consistent naming of `Params` but this requires the removal of the [this code](https://github.com/cosmos/ibc-go/blob/main/modules/core/types/query.go#L14-L26) and for the query servers to be bound to their respective keepers [here](https://github.com/cosmos/ibc-go/blob/main/modules/core/module.go#L136-L140). 

This would also result in the removal of [modules/core/keeper/grpc_query.go](https://github.com/cosmos/ibc-go/blob/main/modules/core/keeper/grpc_query.go)

Thoughts?

**Review by crodriguezvega — COMMENTED** [review]
Thank you, @damiannolan. 

The renaming of `ClientParams` to `Params` is actually already in v6.0.x, so if we should keep it as `ClientParams`, should we revert the PR that did the renaming or should we just backport this PR (and then we get `ConnectionParams` and also the fix for `UpgradedConsensusState` for free)? Any preference?

Since this PR contains actually a feature (the addition of the `ConnectionParams` gRPC) and a bug fix (for the `UpgradedConsensusState` gRPC). How should we handle that with the automated changelog generation? Can we have multiple lines in the squash commit and gitcliff will interpret each? cc: @chatton

**Comment by chatton** [comment]
@crodriguezvega very good question, in the current state of #2697 we will just be looking at the first line of the commit message, so a single entry. It is possible to configure it it to treat every line as an entry, I think this is an excellent use case. Non conventional commits are filtered out, so I believe it should just look at the lines that have the `type: message`.

**Comment by damiannolan** [comment]
I'm happy to pick out the fix as a separate PR if needs @crodriguezvega 
Otherwise I'll add two changelogs for this PR. Let me know what you think? I do think it would be good to backport this to v6

**Review by colin-axner — APPROVED** [review]

**Review by chatton — COMMENTED** [review]
Looks great, since we do now support multiple changelog entries, can we include those in PR description before merge ❤️

**Comment by damiannolan** [comment]
> Looks great, since we do now support multiple changelog entries, can we include those in PR description before merge ❤️

Does it look good to you? Should they be added as the squashed commit msg?
I've also manually added the changelogs here, as I had to remove an old one too!

**Comment by chatton** [comment]
> Does it look good to you? Should they be added as the squashed commit msg? I've also manually added the changelogs here, as I had to remove an old one too!

@damiannolan looks good! You can put the two lines in as the description in the squashed pit, so you can have

PR name

Additional Description
```
imp(core/03-connection): Adding `ConnectionParams` grpc query and CLI to 03-connection.
fix(modules/core/keeper): Fix request wiring for `UpgradedConsensusState` in core query server.
```

One thing to keep in mind is that this message `imp(core/03-connection): Adding ConnectionParams grpc query and CLI to 03-connection.` will render as `Adding ConnectionParams grpc query and CLI to 03-connection.`. i.e. not include `core/03-connection` in the message. You may have intended to do `imp: (core/03-connection) Adding ConnectionParams grpc query and CLI to 03-connection.` if the goal is to include core/03-connection in the changelog entry.

**Review by chatton — APPROVED** [review]
Looks great thank you!

**Pull request merged**
