### PR TITLE
deps: bump cometbft to 0.38.4 in modules.

### PR DESCRIPTION
**Pull request by DimitrisJim**
## Description

closes: #XXXX

### Commit Message / Changelog Entry

```text
type: commit message
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by DimitrisJim** [comment]
seems cometbft 0.38.3 changed an interface that made the cosmossdk version we depend on not compilable:

```
cosmos-sdk@v0.50.3/server/cmt_cmds.go:443:7: cannot use blockStoreDB (variable of type "github.com/cometbft/cometbft-db".DB) as "github.com/cometbft/cometbft-db".Batch value in argument to store.SaveBlockStoreState: "github.com/cometbft/cometbft-db".DB does not implement "github.com/cometbft/cometbft-db".Batch (missing method Write)) (typecheck)
```

**Comment by DimitrisJim** [comment]
might need to hold off on this one.

**Comment by crodriguezvega** [comment]
yes, it looks like... Let's wait for an SDK release that upgrades to it. Thanks for bundling the upgrade in a single PR, though.

**Comment by DimitrisJim** [comment]
bumping to 0.38.4 works out fine!

**Review by colin-axner — APPROVED** [review]

**Review by crodriguezvega — APPROVED** [review]
Thanks, @DimitrisJim!

**Pull request merged**
