### PR TITLE
refactor: separate `24-host` standardised keys by type

### PR DESCRIPTION
**Pull request by damiannolan**
## Description

- Moving `24-host` standardised keys to separate go source files, separated by type

closes: #1791 

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by damiannolan** [comment]
I'm unsure if we should move the parsers functions in this same PR or if it would be better suited to a follow up.
We could optionally add additional parsers for other various paths.

Thoughts?

**Review by chatton — COMMENTED** [review]
What do you think about using a `_keys.go` suffix on each of the files? It would make it even more explicit about what should go in the file.

Re: the parse functions, I see that we use them in other packages as well .e.g. `host.ParseConnectionPath(string(key))`

Maybe not in this PR, but if these are used in multiple packages, I would consider a `parse.ConnectionPath(string(key))` function as an alternative.

**Review by colin-axner — APPROVED** [review]
Layout looks good to me

**Review by crodriguezvega — APPROVED** [review]

**Review by chatton — APPROVED** [review]
LGTM!

**Pull request merged**
