### PR TITLE
chore: remove IsOpen and IsClosed channel methods

### PR DESCRIPTION
**Pull request by damiannolan**
## Description

Removes `IsClosed` and `IsOpen` channel methods.

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against the correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#pull-request-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/build/building-modules/11-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/main/testing/README.md#ibc-testing-package).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/docs/dev/pull-requests.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Review by charleenfei — APPROVED** [review]
🚀

**Comment by damiannolan** [comment]
> should slap bp to 8.1 yea?

Indeed! why not :)

**Review by crodriguezvega — APPROVED** [review]

**Comment by crodriguezvega** [comment]
If we're removing these functions, do you agree on closing [this issue](https://github.com/cosmos/ibc-go/issues/3466) then? :)

**Comment by colin-axner** [comment]
Happy with the change! But it shouldn't have been backported if it is removing functions?

**Comment by colin-axner** [comment]
https://github.com/cosmos/ibc-go/pull/5700

**Comment by colin-axner** [comment]
https://github.com/cosmos/ibc-go/blob/release/v8.0.x/modules/core/04-channel/types/channel.go#L55

**Pull request merged**
